### PR TITLE
Fix db container cleanup

### PR DESCRIPTION
**Pull request by orzeh**

### CODE REVIEW

**Comment by stianlagstad** [comment]
Hey, this seems to work well - thanks! :)

**Comment by stianlagstad** [comment]
Could you write the answer [here](https://stackoverflow.com/questions/46280142/how-should-i-structure-these-gradle-task-dependencies)? Then I'll accept it.

**Comment by orzeh** [comment]
@stianlagstad I don't have SO account.

**Comment by stianlagstad** [comment]
I'll post an answer and point this PR to give you credit, then.

**Pull request merged**
